AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      # please change the bucket name as you prefer since this needs to be globally unique
      BucketName: !Sub "${AWS::Region}-s3-bucket"
      VersioningConfiguration:
        Status: Enabled

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin access identity for cloudfront-infrastructure

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: distribution for cloudfront-infrastructure
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            Id: !Ref S3Bucket
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [
                  "",
                  [
                    "origin-access-identity/cloudfront/",
                    !Ref CloudFrontOriginAccessIdentity,
                  ],
                ]
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          TargetOriginId: !Ref S3Bucket
          ViewerProtocolPolicy: https-only
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none

Outputs:
  CloudfrontDistribution:
    Description: Cloudfront Distribution
    Value: !Ref CloudfrontDistribution
  CloudFrontOriginAccessIdentity:
    Description: Cloudfront Origin Access Identity (OAI)
    Value: !Ref CloudFrontOriginAccessIdentity
  S3Bucket:
    Description: Cloudfront Origin - S3 Bucket
    Value: !Ref S3Bucket
